# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('__acalc', [dirname(__file__)])
        except ImportError:
            import __acalc
            return __acalc
        if fp is not None:
            try:
                _mod = imp.load_module('__acalc', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    __acalc = swig_import_helper()
    del swig_import_helper
else:
    import __acalc
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def sign(*args):
  return __acalc.sign(*args)
sign = __acalc.sign

def degrees(*args):
  return __acalc.degrees(*args)
degrees = __acalc.degrees

def radians(*args):
  return __acalc.radians(*args)
radians = __acalc.radians

def modulo(*args):
  return __acalc.modulo(*args)
modulo = __acalc.modulo

def factorial(*args):
  return __acalc.factorial(*args)
factorial = __acalc.factorial

def binomial(*args):
  return __acalc.binomial(*args)
binomial = __acalc.binomial

def complex_to_r_phi(*args):
  return __acalc.complex_to_r_phi(*args)
complex_to_r_phi = __acalc.complex_to_r_phi

def r_phi_to_complex(*args):
  return __acalc.r_phi_to_complex(*args)
r_phi_to_complex = __acalc.r_phi_to_complex

def maximum(*args):
  return __acalc.maximum(*args)
maximum = __acalc.maximum

def minimum(*args):
  return __acalc.minimum(*args)
minimum = __acalc.minimum

def median(*args):
  return __acalc.median(*args)
median = __acalc.median

def sum(*args):
  return __acalc.sum(*args)
sum = __acalc.sum

def square(*args):
  return __acalc.square(*args)
square = __acalc.square

def multiply(*args):
  return __acalc.multiply(*args)
multiply = __acalc.multiply
# This file is compatible with both classic and new-style classes.


